name: angelswing_dev_test
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management and Dependency Injection
  flutter_riverpod: ^1.0.3

  # HTTP & Connectivity
  dio: ^4.0.4

  # Data Class & Functional Programming
  dartz: ^0.10.1
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0

  # Map & Markers
  google_maps_flutter: ^2.1.1

  # Local storage
  shared_preferences: ^2.0.13

  # Permission checker
  permission_handler: ^9.2.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  freezed: ^1.1.1
  json_serializable: ^6.1.4
  very_good_analysis: ^2.4.0

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
